# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Relationship-HasVariant
version:      0.01
version_from: HasVariant.pm
installdirs:  site
requires:
    Class::DBI:                    0.96
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
